// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD71oHxG2-WsBq-b7GBo-2kANIMw6NQsyY',
    appId: '1:691088546211:web:e720d3235548184e0c2216',
    messagingSenderId: '691088546211',
    projectId: 'car-power-c559c',
    authDomain: 'car-power-c559c.firebaseapp.com',
    storageBucket: 'car-power-c559c.appspot.com',
    measurementId: 'G-X3HY5QGMC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARSwt4h_xKdOqCBdJ3gp-yBLSsLKgYl9A',
    appId: '1:691088546211:android:7880d6cd108ba2d40c2216',
    messagingSenderId: '691088546211',
    projectId: 'car-power-c559c',
    storageBucket: 'car-power-c559c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ0dt_rewiFvaYcAvJjpM4gBx1KjuPUbQ',
    appId: '1:691088546211:ios:6e7822a1c340f3320c2216',
    messagingSenderId: '691088546211',
    projectId: 'car-power-c559c',
    storageBucket: 'car-power-c559c.appspot.com',
    iosClientId: '691088546211-r3g7km9gh6cefs4l9j6652c17vkvusvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.carPower',
  );
}
